publish volume changes for multiple target IQN
hpe-storage/container-storage-provider pull request #10
Opened 2020-01-03 08:40 UTC by wdurairaj

Updated spec.md for multiple target IQN's in publish volume call

2020-01-03 10:12 UTC, shivamerla commented on spec.md
> + * `target_names` json field should be separated by comma, if there are multiple target IQN's needs to be passed to CSI Driver.
@wdurairaj target_names should be returned as an array from CSP and converted to CSV format by CSI driver later.

2020-01-03 10:12 UTC, shivamerla commented on spec.md
> +        "target_names": "iqn.2007-11.com.nimblestorage:group-array1-g3b5de80e54af7a6b"
This should be an array with single entry.

2020-01-04 02:06 UTC, shivamerla approved these changes
lgtm..

2020-01-04 02:07 UTC, shivamerla commented on spec.md
> + * `target_names`  should be returned as an array of target IQN's from CSP and converted to CSV format by CSI driver.
nit: This note is not required for target_names.

2020-01-06 13:45 UTC, rgcostea commented on spec.md
> +#### Response for single target IQN
drop "for single target IQN"

2020-01-06 13:46 UTC, rgcostea commented on spec.md
> + * `target_names`  should be returned as an array of target IQN's from CSP and converted to CSV format by CSI driver.
nit: IQNs from the CSP

2020-01-06 13:46 UTC, rgcostea commented on spec.md
> + #### Response for multiple target IQN
nit: IQNs

2020-01-06 13:48 UTC, rgcostea requested changes
Please also update the https://github.com/hpe-storage/container-storage-provider/blob/master/spec.md#objects table below.

2020-01-06 14:27 UTC, rgcostea commented on spec.md
> +| | target_names | string | only for iscsi | | X |
change string to list\<string\>

2020-01-06 14:44 UTC, rgcostea approved these changes

2020-01-06 14:44 UTC, merged